// common way to init model (to some extent, it's like a table in SQL)

import { Schema, model } from 'mongoose';

const tableSchema = new Schema({
    // _id field auto generated by mongodb
    capacity: {
        type: Number,
        required: [true, "Table must have the capacity!"],
    }
});

const Table = model('Table', tableSchema);

export { Table, tableSchema };
